version: "3.8"

services:
  pgdb:
    image: postgres
    restart: "always"
    container_name: blog-database
    env_file: .env
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data/

  django:
    build:
      context: .
      dockerfile: django.dockerfile
    container_name: blog-web
    restart: "always"
    command: >
      bash -c "
                python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py collectstatic --noinput &&
                python manage.py runserver 0.0.0.0:8000
              "
    volumes:
      - ./volumes/django/media:/usr/src/app/media
      - ./volumes/django/static:/usr/src/app/static
    env_file: .env
    depends_on:
      - pgdb
    links:
      - pgdb

  nginx:
    image: nginx:latest
    container_name: blog-nginx
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/django/static:/usr/src/app/static:ro
      - ./volumes/django/media:/usr/src/app/media:ro
    depends_on:
      - django
    command: >
      sh -c "
        mkdir -p /etc/nginx/ssl &&
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/key.pem -out /etc/nginx/ssl/cert.pem -subj '/CN=localhost' &&
        nginx -g 'daemon off;'
      "
