version: "3.8"

services:
  pgdb:
    image: postgres
    restart: "always"
    container_name: blog-database
    env_file: .env
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data/

  django:
    build:
      context: .
      dockerfile: django.dockerfile
    container_name: blog-web
    restart: "always"
    command: >
      bash -c "
                python manage.py runserver 0.0.0.0:8000
              "
    volumes:
      - ./volumes/django/media:/usr/src/app/media
      - ./volumes/django/static:/usr/src/app/static
      - .:/usr/src/app

    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - pgdb
    links:
      - pgdb
  
  
volumes:
  pgdata:
  django:
